### ISSUE TITLE
Include traffic lamp in commit pop-up

### ISSUE THREAD

**Issue by laurentschall** [alain57/swissas-intellij-plugin#1]
Hi IntelliJ plug-in team,

The plug-in works fine on my side. I would like to submit a wish now.

In the "Are you sure you want to commit" pop-up appearing when the lamp color does not allow to commit, could it be possible to add the link to the build or the traffic lamp itself ?

This would enable to check what's behind the lamp and have a better view of the Jenkin's health to decide to commit or not.

Cheers,
Laurent

**Comment by alain57** [comment]
issue closed in the commit done yesterday
